services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\FileGator\:
        resource: '../src/*'
#        exclude:
#            - '../src/DependencyInjection/'
#            - '../src/Entity/'
#            - '../src/Tests/'
#            - '../src/Resources/'

    App\Bundle\FileGator\Service\FileGatorAppFactory:
        lazy: true
        arguments:
            $parameterBag: '@parameter_bag'
