# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
#    email:
#        enabled: false
##        mailer: acme.custom_mailer_service
##        code_generator: acme.custom_code_generator_service
#        sender_email: no-reply@example.com
#        sender_name: John Doe
#        digits: 7
#        template: admin/auth/2fa.html.twig
##        form_renderer: acme.custom_form_renderer
   