<?php
namespace App\Bundle\FileGator\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function __construct(private string $alias){}
    
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder($this->alias);

        $treeBuilder->getRootNode()
            ->info('Configuration constants for FileGatora configuration.php file')
            ->children()
                ->scalarNode("env")
                    ->defaultValue("%kernel.environment%")
                    ->info("APP_ENV w configuration.php")
                ->end()
                ->scalarNode("path")
                    ->defaultValue("%kernel.project_dir%/src/Bundle/FileGator/public/")
                    ->info("")
                ->end()
                ->scalarNode("public_path")
                    ->defaultValue("/filegator/")
                    ->info("APP_PUBLIC_PATH w configuration.php. Ścieżka ładowania plików w przeglądarce wewnętrz /public")
                ->end()
                ->scalarNode("public_dir")
                    ->defaultValue("%kernel.project_dir%/src/Bundle/FileGator/public/dist")
                    ->info("APP_PUBLIC_DIR w configuration.php")
                ->end()
                ->booleanNode("overwrite_on_upload")
                    ->defaultValue(false)
                    ->info("")
                ->end()
                ->scalarNode("timezone")
                    ->defaultValue("UTC")
                    ->info("https://www.php.net/manual/en/timezones.php")
                ->end()
                ->arrayNode('download_inline')
                    ->scalarPrototype()->end()
                    ->defaultValue(['pdf'])
                    ->info("download inline in the browser, array of extensions, use * for all")
                ->end()
                ->integerNode("lockout_attempts")
                    ->defaultValue(5)
                    ->info("max failed login attempts before ip lockout")
                ->end()
                ->integerNode("lockout_timeout")
                    ->defaultValue(15)
                    ->info("ip lockout timeout in seconds")
                ->end()
                
                ->arrayNode("frontend_config")
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode("app_name")
                            ->defaultValue("Filegator")
                            ->info("")
                        ->end()
                        ->scalarNode("version")
                            ->defaultValue("7.13.0")
                            ->info("APP_VERSION w configuration.php")
                        ->end()
                        ->scalarNode("language")
                            ->defaultValue("english")
                            ->info("")
                        ->end()
                        ->scalarNode("logo")
                            ->defaultValue("https://filegator.io/filegator_logo.svg")
                            ->info("")
                        ->end()
                        ->integerNode("upload_max_size")
                            ->defaultValue(100*1024*1024)
                            ->info("100MB")
                        ->end()
                        ->integerNode("upload_chunk_size")
                            ->defaultValue(1*1024*1024)
                            ->info("1MB")
                        ->end()
                        ->integerNode("upload_simultaneous")
                            ->defaultValue(3)
                            ->info("")
                        ->end()
                        ->scalarNode("default_archive_name")
                            ->defaultValue("archive.zip")
                            ->info("")
                        ->end()
                        ->arrayNode('editable')
                            ->scalarPrototype()->end()
                            ->defaultValue(['.txt', '.css', '.js', '.ts', '.html', '.php', '.json', '.md'])
                            ->info("")
                        ->end()
                        ->scalarNode("date_format")
                            ->defaultValue("YY/MM/DD hh:mm:ss")
                            ->info("see: https://momentjs.com/docs/#/displaying/format/")
                        ->end()
                        ->scalarNode("guest_redirection")
                            ->defaultValue("")
                            ->info("")
                        ->end()
                        ->integerNode("search_simultaneous")
                            ->defaultValue(5)
                            ->info("")
                        ->end()
                        ->arrayNode('filter_entries')
                            ->scalarPrototype()->end()
//                            ->defaultValue([])
                            ->info("")
                        ->end()
                        ->arrayNode('pagination')
                            ->scalarPrototype()->end()
                            ->defaultValue(['', 5, 10, 15])
                            ->info("")
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('services')
                    ->useAttributeAsKey('id')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('handler')
                                ->defaultValue(null)
                                //->isRequired()
                            ->end()
                            ->variableNode('config')
                                ->defaultValue(null)
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}