controllers:
    resource:
        path: ../src/Front/Controller/
        namespace: App\Front\Controller
    type: attribute
    prefix:
        pl: ''
        en: '/en'
        nl: '/nl'
admin:
    resource:
        path: ../src/Admin/Controller/
        namespace: App\Admin\Controller
    type: attribute
    prefix: /admin
    name_prefix: admin_
